# Generated by Django 3.1.7 on 2021-04-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20210409_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='correct',
            field=models.ManyToManyField(blank=True, related_name='correct', to='exams.Question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='failed',
            field=models.ManyToManyField(blank=True, related_name='failed', to='exams.Question'),
        ),
    ]
