# Generated by Django 3.1.7 on 2021-04-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20210416_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='wrongAnswers',
            new_name='wrongAnswer',
        ),
    ]
