# Generated by Django 3.1.7 on 2021-05-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20210416_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correctAnswer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='wrongAnswers',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='exams.answer'),
        ),
    ]
