# Generated by Django 3.2.5 on 2022-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(default='', max_length=500),
        ),
    ]
