# Generated by Django 3.2.5 on 2022-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_question_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
