# Generated by Django 3.2.5 on 2022-04-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Fisico-Química', 'Fisico-Química')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Fisico-Química', 'Fisico-Química')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='subsubject',
            field=models.CharField(choices=[('Geometria', 'Geometria'), ('Funções', 'Funções'), ('Probabilidades e Cálculo Combinatório', 'Probabilidades e Cálculo Combinatório'), ('Números complexos', 'Números complexos'), ('Estatística', 'Estatística'), ('Mecânica', 'Mecânica'), ('Eletricidade', 'Eletricidade'), ('Química', 'Química')], max_length=50),
        ),
    ]
