# Generated by Django 3.2.13 on 2022-06-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_auto_20220429_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resolution',
            field=models.TextField(null=True),
        ),
    ]
