# Generated by Django 3.2.5 on 2022-06-06 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0021_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('paper', 'Paper')], max_length=50),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Typo', 'Gralha no enunciado ou nas opções de resposta'), ('SubmissionError', 'Erro na submissão'), ('QuestionFormatting', 'Pergunta desformatada'), ('LoadingError', 'Página não carrega'), ('ImageError', 'Figura errada ou em falta'), ('Other', 'Outro')], max_length=50)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='exams.question')),
            ],
        ),
    ]
