# Generated by Django 3.2.13 on 2022-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_auto_20220606_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
