# Generated by Django 3.2.13 on 2022-11-11 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.question')),
                ('total_dropdowns', models.IntegerField(default=2)),
            ],
            bases=('exams.question',),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_answers', to='exams.question'),
        ),
        migrations.CreateModel(
            name='FillInTheBlankAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('correct', models.BooleanField(default=False)),
                ('dropdown_number', models.IntegerField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fillintheblank_answers', to='exams.fillintheblankquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
