# Generated by Django 3.2.15 on 2022-09-15 16:55

from django.db import migrations, models
import django.db.models.deletion
import exams.utils


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=exams.utils.rename_image_group)),
                ('source', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.questiongroup'),
        ),
    ]
