# Generated by Django 3.2.13 on 2022-11-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_auto_20220915_1655'),
        ('exams', '0025_auto_20221111_2306'),
    ]

    operations = [
    ]
