# Generated by Django 3.2.15 on 2022-11-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_merge_0025_auto_20220915_1655_0025_auto_20221111_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='source',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='text',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
