# Generated by Django 3.1.7 on 2021-03-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000),
        ),
    ]
