# Generated by Django 3.1.7 on 2021-04-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20210416_1555'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinfo',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question'),
        ),
    ]
