# Generated by Django 3.2.5 on 2021-10-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(related_name='achievements', to='users.Achievement'),
        ),
    ]
