# Generated by Django 3.2.5 on 2021-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_achievement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectinfo',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
