# Generated by Django 3.2.5 on 2021-11-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211130_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='subject',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Física-Química', 'Física-Química'), ('Geral', 'Geral')], default='Geral', max_length=50),
        ),
    ]
