# Generated by Django 3.2.5 on 2022-01-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_achievement_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmation_code',
            field=models.IntegerField(default=0),
        ),
    ]
