# Generated by Django 3.2.13 on 2022-05-27 19:03

from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    Model = apps.get_model('users', 'xpsystem')
    for xps in Model.objects.all().iterator():
        total = 0
        for i in range(xps.currentLevel):
            total += 1000 * 1.5 * i
        
        total += xps.xp

        xps.total_xp = total
        xps.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220429_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpsystem',
            name='total_xp',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='xpsystem',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
