# Generated by Django 3.2.15 on 2022-10-09 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_xpsystem_total_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='users.Achievement'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
