# Generated by Django 3.2.15 on 2022-10-09 17:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20221009_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, default='default_achievement.png', null=True, upload_to=users.models.renameImage),
        ),
    ]
