# Generated by Django 3.2.15 on 2022-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_achievement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='subject',
            field=models.CharField(blank=True, choices=[('Matemática', 'Matemática'), ('Fisico-Química', 'Fisico-Química')], default='Geral', max_length=50),
        ),
    ]
