# Generated by Django 3.2.13 on 2022-11-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20221111_2306'),
        ('users', '0020_alter_achievement_subject'),
    ]

    operations = [
    ]
